# -*- coding: utf-8 -*-
"""Copy of jupyter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14TYuW6VJEMeQzFp9kIfTbPo5XPzC1i5y

# Using Jupyter Notebooks
:label:`sec_jupyter`


This section describes how to edit and run the code
in each section of this book
using the Jupyter Notebook. Make sure you have
installed Jupyter and downloaded the
code as described in
:ref:`chap_installation`.
If you want to know more about Jupyter see the excellent tutorial in
their [documentation](https://jupyter.readthedocs.io/en/latest/).


## Editing and Running the Code Locally

Suppose that the local path of the book's code is `xx/yy/d2l-en/`. Use the shell to change the directory to this path (`cd xx/yy/d2l-en`) and run the command `jupyter notebook`. If your browser does not do this automatically, open http://localhost:8888 and you will see the interface of Jupyter and all the folders containing the code of the book, as shown in :numref:`fig_jupyter00`.

![The folders containing the code of this book.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter00.png?raw=1)
:width:`600px`
:label:`fig_jupyter00`


You can access the notebook files by clicking on the folder displayed on the webpage.
They usually have the suffix ".ipynb".
For the sake of brevity, we create a temporary "test.ipynb" file.
The content displayed after you click it is
shown in :numref:`fig_jupyter01`.
This notebook includes a markdown cell and a code cell. The content in the markdown cell includes "This Is a Title" and "This is text.".
The code cell contains two lines of Python code.

![Markdown and code cells in the "text.ipynb" file.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter01.png?raw=1)
:width:`600px`
:label:`fig_jupyter01`


Double click on the markdown cell to enter edit mode.
Add a new text string "Hello world." at the end of the cell, as shown in :numref:`fig_jupyter02`.

![Edit the markdown cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter02.png?raw=1)
:width:`600px`
:label:`fig_jupyter02`


As demonstrated in :numref:`fig_jupyter03`,
click "Cell" $\rightarrow$ "Run Cells" in the menu bar to run the edited cell.

![Run the cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter03.png?raw=1)
:width:`600px`
:label:`fig_jupyter03`

After running, the markdown cell is shown in :numref:`fig_jupyter04`.

![The markdown cell after running.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter04.png?raw=1)
:width:`600px`
:label:`fig_jupyter04`


Next, click on the code cell. Multiply the elements by 2 after the last line of code, as shown in :numref:`fig_jupyter05`.

![Edit the code cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter05.png?raw=1)
:width:`600px`
:label:`fig_jupyter05`


You can also run the cell with a shortcut ("Ctrl + Enter" by default) and obtain the output result from :numref:`fig_jupyter06`.

![Run the code cell to obtain the output.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter06.png?raw=1)
:width:`600px`
:label:`fig_jupyter06`


When a notebook contains more cells, we can click "Kernel" $\rightarrow$ "Restart & Run All" in the menu bar to run all the cells in the entire notebook. By clicking "Help" $\rightarrow$ "Edit Keyboard Shortcuts" in the menu bar, you can edit the shortcuts according to your preferences.

## Advanced Options

Beyond local editing two things are quite important: editing the notebooks in the markdown format and running Jupyter remotely.
The latter matters when we want to run the code on a faster server.
The former matters since Jupyter's native ipynb format stores a lot of auxiliary data that is
irrelevant to the content,
mostly related to how and where the code is run.
This is confusing for Git, making
reviewing contributions very difficult.
Fortunately there is an alternative---native editing in the markdown format.

### Markdown Files in Jupyter

If you wish to contribute to the content of this book, you need to modify the
source file (md file, not ipynb file) on GitHub.
Using the notedown plugin we
can modify notebooks in the md format directly in Jupyter.


First, install the notedown plugin, run the Jupyter Notebook, and load the plugin:

```
pip install d2l-notedown  # You may need to uninstall the original notedown.
jupyter notebook --NotebookApp.contents_manager_class='notedown.NotedownContentsManager'
```

You may also turn on the notedown plugin by default whenever you run the Jupyter Notebook.
First, generate a Jupyter Notebook configuration file (if it has already been generated, you can skip this step).

```
jupyter notebook --generate-config
```

Then, add the following line to the end of the Jupyter Notebook configuration file (for Linux or macOS, usually in the path `~/.jupyter/jupyter_notebook_config.py`):

```
c.NotebookApp.contents_manager_class = 'notedown.NotedownContentsManager'
```

After that, you only need to run the `jupyter notebook` command to turn on the notedown plugin by default.

### Running Jupyter Notebooks on a Remote Server

Sometimes, you may want to run Jupyter notebooks on a remote server and access it through a browser on your local computer. If Linux or macOS is installed on your local machine (Windows can also support this function through third-party software such as PuTTY), you can use port forwarding:

```
ssh myserver -L 8888:localhost:8888
```

The above string `myserver` is the address of the remote server.
Then we can use http://localhost:8888 to access the remote server `myserver` that runs Jupyter notebooks. We will detail on how to run Jupyter notebooks on AWS instances
later in this appendix.

### Timing

We can use the `ExecuteTime` plugin to time the execution of each code cell in Jupyter notebooks.
Use the following commands to install the plugin:

```
pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
jupyter nbextension enable execute_time/ExecuteTime
```

## Summary

* Using the Jupyter Notebook tool, we can edit, run, and contribute to each section of the book.
* We can run Jupyter notebooks on remote servers using port forwarding.


## Exercises

1. Edit and run the code in this book with the Jupyter Notebook on your local machine.
1. Edit and run the code in this book with the Jupyter Notebook *remotely* via port forwarding.
1. Compare the running time of the operations $\mathbf{A}^\top \mathbf{B}$ and $\mathbf{A} \mathbf{B}$ for two square matrices in $\mathbb{R}^{1024 \times 1024}$. Which one is faster?


[Discussions](https://discuss.d2l.ai/t/421)
"""

import math
import requests
import hashlib
from difflib import SequenceMatcher
import os


# Common dictionary passwords
dictionary_passwords = {
    "123456", "password", "qwerty", "iloveyou", "admin", "abc123",
    "welcome", "letmein", "monkey", "123456789", "password123",
    "dragon", "master", "hello", "freedom", "whatever", "qazwsx"
}

# Keyboard patterns
keyboard_patterns = [
    "qwerty", "asdfgh", "zxcvbn", "qazwsx", "poiuyt",
    "123456", "12345", "123456789", "qwertz", "asdf"
]

# Character set sizes
LOWER = 26
UPPER = 26
DIGITS = 10
SYMBOLS = 32

# Offline breach database (optional)
BREACH_DB_PATH = "breached_passwords.txt"


def load_breach_database():
    if os.path.exists(BREACH_DB_PATH):
        with open(BREACH_DB_PATH, "r") as f:
            return set(line.strip() for line in f)
    return None


BREACH_HASHES = load_breach_database()


# ---------------- PASSWORD CHECK FUNCTIONS ---------------- #

def check_dictionary_attack(password):
    if password.lower() in dictionary_passwords:
        return {
            "Status": "Very Weak (Dictionary Password)",
            "Risk": "CRITICAL",
            "Fix": "Choose a completely different password"
        }
    return None


def detect_keyboard_patterns(password):
    lower_pwd = password.lower()
    for pattern in keyboard_patterns:
        if pattern in lower_pwd:
            return {
                "Risk": "HIGH",
                "Reason": f"Contains keyboard pattern: {pattern}",
                "Fix": "Use random character combinations"
            }
    return None


def check_breached_passwords(password):
    results = {"Status": "Safe", "Breach_Count": 0, "Method": "None"}

    try:
        sha1_hash = hashlib.sha1(password.encode()).hexdigest().upper()
        prefix, suffix = sha1_hash[:5], sha1_hash[5:]

        response = requests.get(
            f"https://api.pwnedpasswords.com/range/{prefix}",
            timeout=5
        )

        if response.status_code == 200:
            hashes = response.text.split("\n")
            for line in hashes:
                hash_suffix, count = line.split(":")
                if hash_suffix == suffix:
                    return {
                        "Status": "EXPOSED ⚠️",
                        "Breach_Count": int(count),
                        "Method": "HaveIBeenPwned API",
                        "Action": "CHANGE IMMEDIATELY!"
                    }
    except Exception:
        pass

    if BREACH_HASHES:
        sha1_hash = hashlib.sha1(password.encode()).hexdigest().upper()
        if sha1_hash in BREACH_HASHES:
            return {
                "Status": "EXPOSED ",
                "Breach_Count": "1000+",
                "Method": "Offline DB",
                "Action": "CHANGE IMMEDIATELY!"
            }

    return results


def suggest_password_improvements(password):
    suggestions = []

    if len(password) < 12:
        suggestions.append(" Increase length to 12+ characters")
    if not any(c.isupper() for c in password):
        suggestions.append(" Add uppercase letters")
    if not any(c.isdigit() for c in password):
        suggestions.append(" Add numbers")
    if not any(not c.isalnum() for c in password):
        suggestions.append(" Add special symbols")

    if not suggestions:
        suggestions.append("✅ Password meets basic requirements")

    return suggestions


def detect_similar_passwords(password, stored_passwords):
    for pwd in stored_passwords:
        if SequenceMatcher(None, password, pwd).ratio() > 0.7:
            return [" Too similar to an old password"]
    return []


def explain_strength_rating(entropy):
    if entropy < 28:
        return "Cracked in seconds"
    elif entropy < 40:
        return "Cracked in minutes"
    elif entropy < 60:
        return "Cracked in days"
    elif entropy < 80:
        return "Cracked in years"
    else:
        return "Cracked in centuries"


# ---------------- STRENGTH CALCULATOR ---------------- #

def check_password_strength(password, guesses_per_second=10**9, stored_passwords=None):
    if stored_passwords is None:
        stored_passwords = []

    result = {
        "Password": password,
        "Length": len(password)
    }

    dict_check = check_dictionary_attack(password)
    if dict_check:
        result.update(dict_check)
        return result

    N = 0
    if any(c.islower() for c in password): N += LOWER
    if any(c.isupper() for c in password): N += UPPER
    if any(c.isdigit() for c in password): N += DIGITS
    if any(not c.isalnum() for c in password): N += SYMBOLS

    entropy = len(password) * math.log2(N) if N else 0
    brute_time = (2 ** (entropy - 1)) / guesses_per_second if entropy else 0

    if entropy < 28:
        strength = "Very Weak"
    elif entropy < 40:
        strength = "Weak"
    elif entropy < 60:
        strength = "Moderate"
    elif entropy < 80:
        strength = "Strong"
    else:
        strength = "Very Strong"

    result.update({
        "Charset": N,
        "Entropy": round(entropy, 2),
        "Crack_Time": f"{brute_time:.2e} seconds",
        "Strength": strength,
        "Breach_Check": check_breached_passwords(password),
        "Keyboard_Patterns": detect_keyboard_patterns(password),
        "Improvements": suggest_password_improvements(password),
        "Reuse_Risk": detect_similar_passwords(password, stored_passwords),
        "Explanation": explain_strength_rating(entropy)
    })

    return result


# ---------------- DASHBOARD ---------------- #

def display_dashboard(result):
    print("\n" + "=" * 60)
    print(" ADVANCED PASSWORD STRENGTH ANALYZER ")
    print("=" * 60)

    if "Strength" not in result:
        print("❌", result["Status"])
        return

    print(f"Password Length: {result['Length']}")
    print(f"Entropy: {result['Entropy']} bits")
    print(f"Strength: {result['Strength']}")
    print(f"Crack Time: {result['Crack_Time']}")

    print("\nSECURITY CHECKS")
    print("Breach Status:", result["Breach_Check"]["Status"])

    if result["Keyboard_Patterns"]:
        print("Keyboard Pattern:", result["Keyboard_Patterns"]["Reason"])

    print("\nSUGGESTIONS")
    for s in result["Improvements"]:
        print("-", s)

    print("\nExplanation:", result["Explanation"])
    print("=" * 60)


# ---------------- MAIN ---------------- #

def main():
    print("Welcome to Advanced Password Strength Analyzer\n")

    stored_passwords = []

    while True:
        password = input("Enter password (or 'quit'): ").strip()
        if password.lower() in ("quit", "exit"):
            break

        result = check_password_strength(password, stored_passwords=stored_passwords)
        display_dashboard(result)


if __name__ == "__main__":
    main()